import "../styles/globals.css";
import AuthProvider from "./src/providers/AuthProvider";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<body className="sm: mx-4">
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	);
}
